name: "lua"
template: "lua.tpl"
sheet: 1
pkcols: [1]
pksep: ":"
list:
  -
    input: "example.xlsx"
    sheet: 1
    pkcols: [1]   
    cols: [-3] # 负数代表不包含，正负不能同时存在
    output: "example_hero.lua"
  -
    input: "example.xlsx"
    sheet: 2
    pkcols: [1,2]   
    cols: [-4]
    output: "example_equip.lua"
