name: "lua"
template: "lua.tpl"
sheet: 1
pkcols: ["A"]
pksep: ":"
list:
  -
    input: "example.xlsx"
    sheet: 1
    pkcols: ["A"]   
    cols: ["-C"] # 负数代表不包含，正负不能同时存在
    output: "example_hero.lua"
  -
    input: "example.xlsx"
    sheet: 2
    pkcols: ["A","B"]   
    cols: ["-D"]
    output: "example_equip.lua"
  -
    input: "example.xlsx"
    sheet: 3
    pkcols: ["B","C"]   
    cols: ["-A", "-B", "-C", "-E"]
    output: "example_role.lua"
